use std::fmt::Write as FmtWrite;
use std::path::Path;

use crate::error;
use crate::runner::SuiteResult;

pub fn generate_markdown_report(
    result: &SuiteResult,
    output_path: &Path,
) -> error::Result<()> {
    let mut md = String::new();

    // Header with pass/fail status
    let status_emoji = if result.total_failed == 0 {
        "PASSED"
    } else {
        "FAILED"
    };
    let _ = writeln!(md, "# difftest Results: {status_emoji}\n");

    // Summary
    let _ = writeln!(
        md,
        "**{total}** tests | **{passed}** passed | **{failed}** failed | **{duration}ms** total\n",
        total = result.results.len(),
        passed = result.total_passed,
        failed = result.total_failed,
        duration = result.duration_ms,
    );

    // Summary table
    md.push_str("| Test | Status | Metrics | Duration |\n");
    md.push_str("|------|--------|---------|----------|\n");

    for test_result in &result.results {
        let status = if test_result.passed {
            "PASS"
        } else {
            "FAIL"
        };

        let metrics_summary: Vec<String> = test_result
            .metrics
            .iter()
            .map(|(name, m)| format!("{name}={:.4}", m.mean))
            .collect();
        let metrics_str = metrics_summary.join(", ");

        let _ = writeln!(
            md,
            "| {name} | {status} | {metrics} | {duration}ms |",
            name = test_result.name,
            status = status,
            metrics = metrics_str,
            duration = test_result.duration_ms,
        );
    }

    md.push('\n');

    // Expandable details for failed tests
    let failed_tests: Vec<_> = result.results.iter().filter(|r| !r.passed).collect();
    if !failed_tests.is_empty() {
        md.push_str("## Failed Tests\n\n");

        for test_result in failed_tests {
            let _ = writeln!(md, "<details>\n<summary><strong>{}</strong></summary>\n", test_result.name);

            md.push_str("| Metric | Mean | Min | Max | Threshold | Status |\n");
            md.push_str("|--------|------|-----|-----|-----------|--------|\n");

            for (name, metric) in &test_result.metrics {
                let status = if metric.passed { "PASS" } else { "FAIL" };
                let _ = writeln!(
                    md,
                    "| {name} | {mean:.4} | {min:.4} | {max:.4} | {threshold:.4} | {status} |",
                    name = name,
                    mean = metric.mean,
                    min = metric.min,
                    max = metric.max,
                    threshold = metric.threshold,
                    status = status,
                );
            }

            md.push_str("\n</details>\n\n");
        }
    }

    // Footer
    md.push_str("---\n*Generated by [difftest](https://github.com/SouKangC/difftest)*\n");

    if let Some(parent) = output_path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }
    std::fs::write(output_path, md)?;
    Ok(())
}
